-- ========================================================================
-- MILITARY ASSET MANAGEMENT SYSTEM - DATABASE SETUP & USER GUIDE
-- ========================================================================

-- ========================================================================
-- 1. CLEANUP: Start Fresh
-- ========================================================================

DROP TABLE IF EXISTS transfer_log CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS asset_transactions CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS bases CASCADE;
DROP TABLE IF EXISTS base CASCADE;

-- ========================================================================
-- 2. CREATE TABLES
-- ========================================================================

CREATE TABLE bases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    commander_name VARCHAR(255),
    garrison_type VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(100) NOT NULL,
    base_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_base FOREIGN KEY (base_id) REFERENCES bases(id) ON DELETE SET NULL
);

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    serial_number VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL DEFAULT 'ACTIVE',
    current_base_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_asset_base FOREIGN KEY (current_base_id) REFERENCES bases(id) ON DELETE RESTRICT
);

CREATE TABLE asset_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    transaction_type VARCHAR(100),
    from_base_id BIGINT,
    to_base_id BIGINT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_asset_transaction FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE
);

CREATE TABLE transfer_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name VARCHAR(255) NOT NULL,
    source_base VARCHAR(255),
    dest_base VARCHAR(255),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR(100) NOT NULL,
    asset_name VARCHAR(255),
    details VARCHAR(500),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================================================
-- 3. CREATE INDEXES
-- ========================================================================

CREATE INDEX idx_assets_serial_number ON assets(serial_number);
CREATE INDEX idx_assets_status ON assets(status);
CREATE INDEX idx_assets_current_base ON assets(current_base_id);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_audit_log_timestamp ON audit_log(timestamp);
CREATE INDEX idx_transfer_log_timestamp ON transfer_log(timestamp);

-- ========================================================================
-- 4. INSERT BASE DATA
-- ========================================================================

INSERT INTO bases (name, location, commander_name, garrison_type) VALUES 
('Indraprastha HQ', 'New Delhi', 'Brig. Suryadev Singh', 'Headquarters'),
('Siachen Base Camp', 'Ladakh', 'Col. Vikram Batra Memorial', 'High Altitude'),
('Dipatoli Cantonment', 'Ranchi', 'Maj. Ravi Kumar', 'Training Center'),
('Fort Alpha', 'Mumbai', 'Col. Ashok Verma', 'Naval'),
('Camp Bravo', 'Pune', 'Brig. Prakash Sharma', 'Storage');

-- ========================================================================
-- 5. USER SETUP INSTRUCTIONS (MANUAL REGISTRATION)
-- ========================================================================
/*
   IMPORTANT: The 'users' table is intentionally left empty.
   You must register users manually via Postman to ensure passwords are 
   hashed correctly by the server.

   API URL: https://militaryassetmanagement-2tbh.onrender.com/api/auth/register
   Method: POST
   Content-Type: application/json

   --- COPY & PASTE THESE JSON BODIES INTO POSTMAN ---

   1. ADMIN USER (Global Access)
   {
     "username": "admin_user",
     "password": "password123",
     "role": "ADMIN",
     "baseId": null
   }

   2. LOGISTICS OFFICER (Indraprastha HQ)
   {
     "username": "logistics_officer",
     "password": "password123",
     "role": "LOGISTICS",
     "baseId": 1
   }

   3. COMMANDER - DELHI (Indraprastha HQ)
   {
     "username": "commander_delhi",
     "password": "password123",
     "role": "COMMANDER",
     "baseId": 1
   }

   4. COMMANDER - SIACHEN (Base ID 2)
   {
     "username": "commander_siachen",
     "password": "password123",
     "role": "COMMANDER",
     "baseId": 2
   }

   5. COMMANDER - RANCHI (Base ID 3)
   {
     "username": "commander_ranchi",
     "password": "password123",
     "role": "COMMANDER",
     "baseId": 3
   }

   6. COMMANDER - MUMBAI (Base ID 4)
   {
     "username": "commander_mumbai",
     "password": "password123",
     "role": "COMMANDER",
     "baseId": 4
   }

   7. COMMANDER - PUNE (Base ID 5)
   {
     "username": "commander_pune",
     "password": "password123",
     "role": "COMMANDER",
     "baseId": 5
   }
*/

-- ========================================================================
-- 6. INSERT ASSET DATA
-- ========================================================================

INSERT INTO assets (name, serial_number, type, status, current_base_id) VALUES 
('T-90 Bhishma Tank', 'TANK-IND-001', 'VEHICLE', 'ACTIVE', 1),
('T-90 Bhishma Tank', 'TANK-IND-002', 'VEHICLE', 'ASSIGNED', 2),
('T-90 Bhishma Tank', 'TANK-IND-003', 'VEHICLE', 'ACTIVE', 3),
('Ashok Leyland Stallion', 'TRUCK-IND-101', 'VEHICLE', 'ACTIVE', 3),
('Ashok Leyland Stallion', 'TRUCK-IND-102', 'VEHICLE', 'EXPENDED', 2),
('Ashok Leyland Stallion', 'TRUCK-IND-103', 'VEHICLE', 'ASSIGNED', 4),
('Tata Safari GS800', 'LMV-IND-005', 'VEHICLE', 'ASSIGNED', 1),
('Tata Safari GS800', 'LMV-IND-006', 'VEHICLE', 'ACTIVE', 5),
('Maruti Gypsy King', 'LMV-IND-009', 'VEHICLE', 'ACTIVE', 3),
('Mahindra Bolero Pik-Up', 'LMV-IND-010', 'VEHICLE', 'ASSIGNED', 2),
('Bharatiya Armoured Vehicle', 'BAV-IND-001', 'VEHICLE', 'ACTIVE', 1),
('HMMWV Humvee', 'HMMWV-IND-001', 'VEHICLE', 'ASSIGNED', 4),
('INSAS Rifle 5.56mm', 'WPN-RIF-101', 'WEAPON', 'ASSIGNED', 3),
('INSAS Rifle 5.56mm', 'WPN-RIF-102', 'WEAPON', 'ACTIVE', 3),
('INSAS Rifle 5.56mm', 'WPN-RIF-103', 'WEAPON', 'ACTIVE', 1),
('AK-203 Assault Rifle', 'WPN-AK-201', 'WEAPON', 'ACTIVE', 2),
('AK-203 Assault Rifle', 'WPN-AK-202', 'WEAPON', 'ASSIGNED', 2),
('AK-203 Assault Rifle', 'WPN-AK-203', 'WEAPON', 'ACTIVE', 5),
('Sig Sauer 716 Rifle', 'WPN-SIG-301', 'WEAPON', 'ACTIVE', 1),
('Sig Sauer 716 Rifle', 'WPN-SIG-302', 'WEAPON', 'ASSIGNED', 4),
('Dragunov SVD Sniper', 'WPN-SNP-055', 'WEAPON', 'ASSIGNED', 2),
('Dragunov SVD Sniper', 'WPN-SNP-056', 'WEAPON', 'ACTIVE', 3),
('Carl Gustaf M4 Launcher', 'RL-IND-001', 'WEAPON', 'EXPENDED', 2),
('Panzerfaust 3 Launcher', 'RL-IND-002', 'WEAPON', 'ACTIVE', 1),
('9mm Service Pistol', 'WPN-PST-009', 'WEAPON', 'ACTIVE', 1),
('9mm Service Pistol', 'WPN-PST-010', 'WEAPON', 'ASSIGNED', 2),
('12 Gauge Combat Shotgun', 'WPN-SHG-001', 'WEAPON', 'ACTIVE', 5),
('Heckler Koch MP5', 'WPN-MP5-001', 'WEAPON', 'ASSIGNED', 4),
('5.56mm Ammo Crate (1000rds)', 'AMMO-556-001', 'AMMUNITION', 'ACTIVE', 3),
('5.56mm Ammo Crate (1000rds)', 'AMMO-556-002', 'AMMUNITION', 'ACTIVE', 1),
('7.62mm Ammo Crate (500rds)', 'AMMO-762-001', 'AMMUNITION', 'EXPENDED', 2),
('7.62mm Ammo Crate (500rds)', 'AMMO-762-002', 'AMMUNITION', 'ACTIVE', 5),
('155mm Artillery Shells', 'AMMO-ART-901', 'AMMUNITION', 'ACTIVE', 1),
('155mm Artillery Shells', 'AMMO-ART-902', 'AMMUNITION', 'ASSIGNED', 3),
('9mm Pistol Ammo Box', 'AMMO-9MM-001', 'AMMUNITION', 'ACTIVE', 1),
('Mortar Rounds 81mm', 'AMMO-MOR-101', 'AMMUNITION', 'ACTIVE', 2),
('Hand Grenades (RDG)', 'AMMO-GRN-001', 'AMMUNITION', 'ACTIVE', 4),
('Night Vision Goggles', 'EQ-NVG-101', 'WEAPON', 'ASSIGNED', 2),
('Thermal Imaging System', 'EQ-THERMAL-001', 'WEAPON', 'ACTIVE', 1),
('Satellite Communication System', 'EQ-SAT-COM-001', 'WEAPON', 'ACTIVE', 5);

-- ========================================================================
-- 7. INSERT LOG DATA
-- ========================================================================

INSERT INTO audit_log (action_type, asset_name, details, timestamp) VALUES 
('PURCHASE', 'T-90 Bhishma Tank', 'Base: Indraprastha HQ', NOW() - INTERVAL '30 days'),
('TRANSFER', 'T-90 Bhishma Tank', 'Transferred to Siachen Base Camp', NOW() - INTERVAL '15 days'),
('ASSIGN', 'INSAS Rifle 5.56mm', 'To: Sepoy Singh (Ranchi)', NOW() - INTERVAL '10 days'),
('EXPEND', 'Carl Gustaf M4 Launcher', 'Destroyed during training exercise', NOW() - INTERVAL '2 days'),
('ASSIGN', 'Night Vision Goggles', 'To: Capt. Arun Kumar', NOW());

INSERT INTO transfer_log (asset_name, source_base, dest_base, timestamp) VALUES 
('T-90 Bhishma Tank', 'Indraprastha HQ', 'Siachen Base Camp', NOW() - INTERVAL '15 days'),
('INSAS Rifle 5.56mm', 'Indraprastha HQ', 'Dipatoli Cantonment', NOW() - INTERVAL '12 days'),
('Tata Safari GS800', 'Camp Bravo', 'Indraprastha HQ', NOW());